### ISSUE TITLE
Android App crashes with fatal error on successful connection establishment

### ISSUE THREAD

**Issue by shivanshtalwar0** [cloudwebrtc/flutter-webrtc#1006]
**Describe the bug**
encountered the bug while running  [video call example](https://github.com/flutterjanus/flutter_janus_client/blob/master/example/lib/typed_examples/video_call.dart) 
attaching logs of error below.

E/MethodChannel#FlutterWebRTC.Method(30686): Failed to handle method call
E/MethodChannel#FlutterWebRTC.Method(30686): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.cloudwebrtc.webrtc.FlutterRTCVideoRenderer.checkMediaStream(java.lang.String)' on a null object reference
E/MethodChannel#FlutterWebRTC.Method(30686): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:358)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at android.os.Looper.loop(Looper.java:236)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/MethodChannel#FlutterWebRTC.Method(30686): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/DartMessenger(30686): Uncaught exception in binary message listener
E/DartMessenger(30686): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(30686): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/DartMessenger(30686): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:282)
E/DartMessenger(30686): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(30686): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/DartMessenger(30686): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(30686): 	at android.os.Handler.handleCallback(Handler.java:938)
E/DartMessenger(30686): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(30686): 	at android.os.Looper.loop(Looper.java:236)
E/DartMessenger(30686): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
E/DartMessenger(30686): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(30686): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/DartMessenger(30686): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
W/FlutterWebRTCPlugin(30686): FlutterRTCVideoRenderer.setVideoTrack, set video track to 04721eda-ac7e-437b-8de6-b453db221834
I/org.webrtc.Logging(30686): EglRenderer: Releasing.
I/org.webrtc.Logging(30686): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging(30686): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(30686): EglRenderer: Releasing done.
I/org.webrtc.Logging(30686): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging(30686): EglRenderer: EglBase.create shared context
I/org.webrtc.Logging(30686): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging(30686): HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=100, mime=video/x-vnd.on2.vp8, width=1280, bitrate-mode=2, bitrate=300000, frame-rate=60.0, height=720}
I/ExtendedACodec(30686): setupVideoEncoder()
W/OMXUtils(30686): do not know color format 0x7fa30c06 = 2141391878
W/OMXUtils(30686): do not know color format 0x7fa30c04 = 2141391876
W/OMXUtils(30686): do not know color format 0x7fa30c00 = 2141391872
W/OMXUtils(30686): do not know color format 0x7fa30c09 = 2141391881
W/OMXUtils(30686): do not know color format 0x7fa30c0a = 2141391882
W/OMXUtils(30686): do not know color format 0x7fa30c08 = 2141391880
W/OMXUtils(30686): do not know color format 0x7fa30c07 = 2141391879
W/OMXUtils(30686): do not know color format 0x7f000789 = 2130708361
I/ACodec  (30686): [OMX.qcom.video.encoder.vp8] cannot encode HDR static metadata. Ignoring.
I/ACodec  (30686): setupVideoEncoder succeeded
I/ExtendedACodec(30686): [OMX.qcom.video.encoder.vp8] configure, AMessage : AMessage(what = 'conf', target = 10) = {
I/ExtendedACodec(30686):   int32_t color-format = 2130708361
I/ExtendedACodec(30686):   int32_t i-frame-interval = 100
I/ExtendedACodec(30686):   string mime = "video/x-vnd.on2.vp8"
I/ExtendedACodec(30686):   int32_t width = 1280
I/ExtendedACodec(30686):   int32_t bitrate-mode = 2
I/ExtendedACodec(30686):   int32_t bitrate = 300000
I/ExtendedACodec(30686):   float frame-rate = 60.000000
I/ExtendedACodec(30686):   int32_t height = 720
I/ExtendedACodec(30686):   int32_t flags = 1
I/ExtendedACodec(30686):   int32_t encoder = 1
I/ExtendedACodec(30686): }
W/OMXUtils(30686): do not know color format 0x7f000789 = 2130708361
I/ACodec  (30686): [OMX.qcom.video.encoder.vp8] input format is AMessage(what = 0x00000000) = {
I/ACodec  (30686):   string mime = "video/raw"
I/ACodec  (30686):   int32_t stride = 1280
I/ACodec  (30686):   int32_t slice-height = 720
I/ACodec  (30686):   int32_t color-format = 2130708361
I/ACodec  (30686):   int32_t color-range = 0
I/ACodec  (30686):   int32_t color-standard = 0
I/ACodec  (30686):   int32_t color-transfer = 0
I/ACodec  (30686):   int32_t width = 1280
I/ACodec  (30686):   int32_t height = 720
I/ACodec  (30686): }
I/ACodec  (30686): [OMX.qcom.video.encoder.vp8] output format is AMessage(what = 0x00000000) = {
I/ACodec  (30686):   int32_t bitrate = 300000
I/ACodec  (30686):   int32_t max-bitrate = 300000
I/ACodec  (30686):   int32_t frame-rate = 60
I/ACodec  (30686):   string mime = "video/x-vnd.on2.vp8"
I/ACodec  (30686):   int32_t width = 1280
I/ACodec  (30686):   int32_t height = 720
I/ACodec  (30686): }
I/org.webrtc.Logging(30686): EglBase14Impl: Using OpenGL ES version 2
I/ACodec  (30686): Need to setDefaultCodecColorAspectsIfNeeded
I/org.webrtc.Logging(30686): EglRenderer: Duration: 4001 ms. Frames received: 34. Dropped: 0. Rendered: 34. Render fps: 8.5. Average render time: 1827 us. Average swapBuffer time: 696 us.
I/org.webrtc.Logging(30686): HardwareVideoEncoder: Releasing MediaCodec on output thread
I/org.webrtc.Logging(30686): HardwareVideoEncoder: Release on output thread done
E/libc    (30686): Access denied finding property "ro.vendor.media.video.frc.support"
I/org.webrtc.Logging(30686): HardwareVideoEncoder: initEncode: 960 x 528. @ 300kbps. Fps: 60 Use surface mode: true
I/OMXClient(30686): IOmx service obtained
I/org.webrtc.Logging(30686): HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=100, mime=video/x-vnd.on2.vp8, width=960, bitrate-mode=2, bitrate=300000, frame-rate=60.0, height=528}
I/ExtendedACodec(30686): setupVideoEncoder()
W/OMXUtils(30686): do not know color format 0x7fa30c06 = 2141391878
W/OMXUtils(30686): do not know color format 0x7fa30c04 = 2141391876
W/OMXUtils(30686): do not know color format 0x7fa30c00 = 2141391872
W/OMXUtils(30686): do not know color format 0x7fa30c09 = 2141391881
W/OMXUtils(30686): do not know color format 0x7fa30c0a = 2141391882
W/OMXUtils(30686): do not know color format 0x7fa30c08 = 2141391880
W/OMXUtils(30686): do not know color format 0x7fa30c07 = 2141391879
W/OMXUtils(30686): do not know color format 0x7f000789 = 2130708361
I/ACodec  (30686): [OMX.qcom.video.encoder.vp8] cannot encode HDR static metadata. Ignoring.
I/ACodec  (30686): setupVideoEncoder succeeded
I/ExtendedACodec(30686): [OMX.qcom.video.encoder.vp8] configure, AMessage : AMessage(what = 'conf', target = 13) = {
I/ExtendedACodec(30686):   int32_t color-format = 2130708361
I/ExtendedACodec(30686):   int32_t i-frame-interval = 100
I/ExtendedACodec(30686):   string mime = "video/x-vnd.on2.vp8"
I/ExtendedACodec(30686):   int32_t width = 960
I/ExtendedACodec(30686):   int32_t bitrate-mode = 2
I/ExtendedACodec(30686):   int32_t bitrate = 300000
I/ExtendedACodec(30686):   float frame-rate = 60.000000
I/ExtendedACodec(30686):   int32_t height = 528
I/ExtendedACodec(30686):   int32_t flags = 1
I/ExtendedACodec(30686):   int32_t encoder = 1
I/ExtendedACodec(30686): }
W/OMXUtils(30686): do not know color format 0x7f000789 = 2130708361
I/ACodec  (30686): [OMX.qcom.video.encoder.vp8] input format is AMessage(what = 0x00000000) = {
I/ACodec  (30686):   string mime = "video/raw"
I/ACodec  (30686):   int32_t stride = 960
I/ACodec  (30686):   int32_t slice-height = 528
I/ACodec  (30686):   int32_t color-format = 2130708361
I/ACodec  (30686):   int32_t color-range = 0
I/ACodec  (30686):   int32_t color-standard = 0
I/ACodec  (30686):   int32_t color-transfer = 0
I/ACodec  (30686):   int32_t width = 960
I/ACodec  (30686):   int32_t height = 528
I/ACodec  (30686): }
D/FlutterWebRTCPlugin(30686): onSelectedCandidatePairChanged
I/ACodec  (30686): [OMX.qcom.video.encoder.vp8] output format is AMessage(what = 0x00000000) = {
I/ACodec  (30686):   int32_t bitrate = 300000
I/ACodec  (30686):   int32_t max-bitrate = 300000
I/ACodec  (30686):   int32_t frame-rate = 60
I/ACodec  (30686):   string mime = "video/x-vnd.on2.vp8"
I/ACodec  (30686):   int32_t width = 960
I/ACodec  (30686):   int32_t height = 528
I/ACodec  (30686): }
I/org.webrtc.Logging(30686): EglBase14Impl: Using OpenGL ES version 2
I/ACodec  (30686): Need to setDefaultCodecColorAspectsIfNeeded
I/org.webrtc.Logging(30686): CameraCapturer: Stop capture
I/org.webrtc.Logging(30686): CameraCapturer: Stop capture: Nulling session
I/org.webrtc.Logging(30686): CameraCapturer: Stop capture done
I/org.webrtc.Logging(30686): CameraCapturer: dispose
I/org.webrtc.Logging(30686): CameraCapturer: Stop capture
I/org.webrtc.Logging(30686): CameraCapturer: Stop capture: No session open
I/org.webrtc.Logging(30686): CameraCapturer: Stop capture done
I/org.webrtc.Logging(30686): Camera2Session: Stop camera2 session on camera 1
I/org.webrtc.Logging(30686): Camera2Session: Stop internal
I/org.webrtc.Logging(30686): SurfaceTextureHelper: stopListening()
W/FlutterWebRTCPlugin(30686): FlutterRTCVideoRenderer.setVideoTrack, set video track to null
W/FlutterWebRTCPlugin(30686): FlutterRTCVideoRenderer.setVideoTrack, set video track to null
I/org.webrtc.Logging(30686): EglRenderer: Releasing.
I/org.webrtc.Logging(30686): GlShader: Deleting shader.
I/org.webrtc.Logging(30686): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging(30686): EglRenderer: Releasing done.
I/org.webrtc.Logging(30686): EglRenderer: Releasing.
I/org.webrtc.Logging(30686): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(30686): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging(30686): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(30686): EglRenderer: Releasing done.
I/org.webrtc.Logging(30686): HardwareVideoEncoder: Releasing MediaCodec on output thread
I/org.webrtc.Logging(30686): HardwareVideoEncoder: Release on output thread done
I/org.webrtc.Logging(30686): HardwareVideoEncoder: initEncode: 640 x 352. @ 300kbps. Fps: 60 Use surface mode: true
D/MediaCodec(30686): MediaCodec::reclaim(0xb4000070619f0a00) OMX.qcom.video.encoder.vp8
E/libc    (30686): Access denied finding property "ro.vendor.media.video.frc.support"
W/MediaCodec(30686): Received kWhatReleaseCompleted in state 0
I/OMXClient(30686): IOmx service obtained
I/org.webrtc.Logging(30686): HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=100, mime=video/x-vnd.on2.vp8, width=640, bitrate-mode=2, bitrate=300000, frame-rate=60.0, height=352}
I/ExtendedACodec(30686): setupVideoEncoder()
W/OMXUtils(30686): do not know color format 0x7fa30c06 = 2141391878
W/OMXUtils(30686): do not know color format 0x7fa30c04 = 2141391876
W/OMXUtils(30686): do not know color format 0x7fa30c00 = 2141391872
W/OMXUtils(30686): do not know color format 0x7fa30c09 = 2141391881
W/OMXUtils(30686): do not know color format 0x7fa30c0a = 2141391882
W/OMXUtils(30686): do not know color format 0x7fa30c08 = 2141391880
W/OMXUtils(30686): do not know color format 0x7fa30c07 = 2141391879
W/OMXUtils(30686): do not know color format 0x7f000789 = 2130708361
I/ACodec  (30686): [OMX.qcom.video.encoder.vp8] cannot encode HDR static metadata. Ignoring.
I/ACodec  (30686): setupVideoEncoder succeeded
I/ExtendedACodec(30686): [OMX.qcom.video.encoder.vp8] configure, AMessage : AMessage(what = 'conf', target = 16) = {
I/ExtendedACodec(30686):   int32_t color-format = 2130708361
I/ExtendedACodec(30686):   int32_t i-frame-interval = 100
I/ExtendedACodec(30686):   string mime = "video/x-vnd.on2.vp8"
I/ExtendedACodec(30686):   int32_t width = 640
I/ExtendedACodec(30686):   int32_t bitrate-mode = 2
I/ExtendedACodec(30686):   int32_t bitrate = 300000
I/ExtendedACodec(30686):   float frame-rate = 60.000000
I/ExtendedACodec(30686):   int32_t height = 352
I/ExtendedACodec(30686):   int32_t flags = 1
I/ExtendedACodec(30686):   int32_t encoder = 1
I/ExtendedACodec(30686): }
W/OMXUtils(30686): do not know color format 0x7f000789 = 2130708361
I/ACodec  (30686): [OMX.qcom.video.encoder.vp8] input format is AMessage(what = 0x00000000) = {
I/ACodec  (30686):   string mime = "video/raw"
I/ACodec  (30686):   int32_t stride = 640
I/ACodec  (30686):   int32_t slice-height = 352
I/ACodec  (30686):   int32_t color-format = 2130708361
I/ACodec  (30686):   int32_t color-range = 0
I/ACodec  (30686):   int32_t color-standard = 0
I/ACodec  (30686):   int32_t color-transfer = 0
I/ACodec  (30686):   int32_t width = 640
I/ACodec  (30686):   int32_t height = 352
I/ACodec  (30686): }
I/ACodec  (30686): [OMX.qcom.video.encoder.vp8] output format is AMessage(what = 0x00000000) = {
I/ACodec  (30686):   int32_t bitrate = 300000
I/ACodec  (30686):   int32_t max-bitrate = 300000
I/ACodec  (30686):   int32_t frame-rate = 60
I/ACodec  (30686):   string mime = "video/x-vnd.on2.vp8"
I/ACodec  (30686):   int32_t width = 640
I/ACodec  (30686):   int32_t height = 352
I/ACodec  (30686): }
I/org.webrtc.Logging(30686): EglBase14Impl: Using OpenGL ES version 2
I/ACodec  (30686): Need to setDefaultCodecColorAspectsIfNeeded
W/BpBinder(30686): PerfMonitor binderTransact :  time=285ms interface=android.hardware.camera2.ICameraDeviceUser code=1
I/org.webrtc.Logging(30686): Camera2Session: Stop done
I/org.webrtc.Logging(30686): Camera2Session: Camera device closed.
D/FlutterWebRTCPlugin(30686): CameraEventsHandler.onFirstFrameAvailable
D/FlutterWebRTCPlugin(30686): onConnectionChangeCONNECTED

**To Reproduce**
Run videocall example on two different android devices and try to call other phone from first phone, after accepting the call it crashes with the above error logs and screen goes complete black on both devices 

**Expected behavior**
it should not crash
**Platform information**

* **Flutter version**: 
[✓] Flutter (Channel stable, 3.0.4, on Linux Mint 20.3 5.16.12, locale en_IN)
    • Flutter version 3.0.4 at /home/shivansh/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (2 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc3)
    • Android SDK at /home/shivansh/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc3
    • ANDROID_HOME = /home/shivansh/Android/Sdk
    • ANDROID_SDK_ROOT = /home/shivansh/Android/Sdk
    • Java binary at:
      /home/shivansh/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.
      7628.21.2111.8309675/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at
      /home/shivansh/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.
      7628.21.2111.8309675
    • Flutter plugin version 69.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • POCO F1 (mobile) • 2f5b2675 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)  • linux    • linux-x64      • Linux Mint 20.3 5.16.12
    • Chrome (web)     • chrome   • web-javascript • Google Chrome
      103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

* **Plugin version**: 0.8.12
* **OS**:  Android
* **OS version**: 31

**Comment by ycherniavskyi** [comment]
Does it crash for audio call?

**Comment by shivanshtalwar0** [comment]
Nope for video call basically after ice connection is connected camera is closed and screen goes black on both screen

**Comment by shivanshtalwar0** [comment]
@cloudwebrtc please take a look into it as it seems like a critical bug

**Comment by MuZiLee** [comment]
@shivanshtalwar0 Did you solve your problem?

**Comment by cloudwebrtc** [comment]
Yesterday I tested a related issue. If RTCRenderer is repeatedly created without calling dispose to release SurefaceHelper, it will cause DecoderQueue initialization to fail after accumulating for a certain period of time, resulting in a crash.

The fix is to call after each end call to properly release all renderers
_localRenderer.dispose();
_remoteRenderer.disopose();

**Comment by bugrevealingbme** [comment]
++still have

**Comment by rguntha** [comment]
This issue is occurring for me continuously.

It is happening as soon as the first call opens the localRenderer. So it is not related to disposing the renderers as indicated by @cloudwebrtc 

[https://github.com/flutter-webrtc/flutter-webrtc/issues/1105#issuecomment-1267630614](url)

The above fix helped me in resolving the issue.
