### ISSUE TITLE
PlatformException when trying to invoke createSurfaceTexture.

### ISSUE THREAD

**Issue by rushib1** [cloudwebrtc/flutter-webrtc#115]
This is the exception I get when I try to initialize the RTCVideoRenderer. I have followed this article [background execution with dart](https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124)

By now I think you all got where I am coming from. I am trying to run the dart code when I get a update from firebase to initiate the rtc handshake.

Can any one suggest what I should do here. I can sacrifice the support of ios if required.

```
E/flutter ( 2286): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'io.flutter.view.TextureRegistry$SurfaceTextureEntry io.flutter.view.TextureRegistry.createSurfaceTexture()' on a null object reference, null)
E/flutter ( 2286): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 2286): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 2286): <asynchronous suspension>
E/flutter ( 2286): #2      RTCVideoRenderer.initialize (package:flutter_webrtc/rtc_video_view.dart:29:24)
E/flutter ( 2286): <asynchronous suspension>
E/flutter ( 2286): #3      _MyAppState.initializeSocket (package:background_plugin_example/main.dart:65:28)
E/flutter ( 2286): <asynchronous suspension>
E/flutter ( 2286): #4      _MyAppState.helloWorld (package:background_plugin_example/main.dart:188:11)
E/flutter ( 2286): <asynchronous suspension>
E/flutter ( 2286): #5      callbackDispatcher.<anonymous closure> (package:background_plugin/background_plugin.dart:43:8)
E/flutter ( 2286): <asynchronous suspension>
E/flutter ( 2286): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:383:55)
E/flutter ( 2286): <asynchronous suspension>
E/flutter ( 2286): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:351:54)
E/flutter ( 2286): #8      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:76:33)
E/flutter ( 2286): <asynchronous suspension>
E/flutter ( 2286): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:263:15)
E/flutter ( 2286): #10     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 2286): #11     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 2286): #12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 2286): #13     _invoke3 (dart:ui/hooks.dart:262:10)
E/flutter ( 2286): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:136:5)
E/flutter ( 2286): 

```

Complete code that runs from background trigger
```
  static Map<String, dynamic> configuration = {
    "iceServers": [
      {"url": "stun:stun.l.google.com:19302"},
    ],
    "sdpSemantics": "unified-plan"
  };

  static final Map<String, dynamic> _constraints = {
    'mandatory': {
      'OfferToReceiveAudio': true,
      'OfferToReceiveVideo': true,
    },
    'optional': [],
  };

  static final Map<String, dynamic> _config = {
    'mandatory': {},
    'optional': [
      {'DtlsSrtpKeyAgreement': true},
    ],
  };

  static final Map<String, dynamic> mediaConstraints = {
    "audio": {
      "channelCount": "2",
      "sampleRate": "48000"
    },
    "video": false
  };

  static int a = 420;
  static int b = 401;

  static void initializeSocket(
      RTCVideoRenderer _remoteContainer, RTCVideoRenderer _localContainer,
      RTCPeerConnection _remotePeer, RTCPeerConnection _localPeer, IOWebSocketChannel channel
      ) async {
    assert(_remoteContainer != null, "remote container should not be null");
    assert(_localContainer != null, "remote container should not be null");
    await _remoteContainer.initialize();
    await _localContainer.initialize();
    channel = IOWebSocketChannel.connect('ws://192.168.31.192:8080/echo?id=$a');
    channel.stream.listen((data) async {
      data = json.decode(data);
      switch(data['type']) {
        case "offer": {
          _localPeer = await createPeerConnection(configuration, _config);
          MediaStream m = await navigator.getUserMedia(mediaConstraints);
          _localContainer.srcObject = m;
          _localPeer.addStream(m);
          _localPeer.onIceCandidate = (RTCIceCandidate candidate) {
            channel.sink.add(json.encode({
              "type": "candidate",
              "id": "$b",
              "message": {
                "candidate": {
                  "candidate": candidate.candidate,
                  "sdpMid": candidate.sdpMid,
                  "sdpMlineIndex": candidate.sdpMlineIndex
                }
              }
            }));
          };
          _localPeer.onAddStream = (MediaStream m) {
            _remoteContainer.srcObject = m;
          };

          _localPeer.setRemoteDescription(RTCSessionDescription(data['message']['sdp'], data['message']['type']));
          _localPeer.createAnswer(_constraints).then((RTCSessionDescription desc) {
            _localPeer.setLocalDescription(desc);
            channel.sink.add(json.encode({
              "type": "answer",
              "id": "$b",
              "message": {
                "type": desc.type,
                "sdp": desc.sdp
              }
            }));
          });
          break;
        }
        case "answer": {
          _localPeer.setRemoteDescription(RTCSessionDescription(
              data['message']['sdp'],
              data['message']['type']
          ));
          break;
        }
        case "candidate": {
          if (_localPeer != null) {
            RTCIceCandidate candidate = new RTCIceCandidate(
                data['message']['candidate']['candidate'].toString(),
                data['message']['candidate']['sdpMid'].toString(),
                int.parse(data['message']['candidate']['sdpMLineIndex'] ?? "0"));
            _localPeer?.addCandidate(candidate);
          }
        }
      }
    });
  }

  static initiateCall(RTCVideoRenderer _remoteContainer, RTCVideoRenderer _localContainer,
      RTCPeerConnection _remotePeer, RTCPeerConnection _localPeer, IOWebSocketChannel channel) async {
    _localPeer = await createPeerConnection(configuration, _config);
    MediaStream m = await navigator.getUserMedia(mediaConstraints);
    _localContainer.srcObject = m;
    _localPeer.addStream(m);

    _localPeer.onIceGatheringState = (RTCIceGatheringState ice) {
      if (ice == RTCIceGatheringState.RTCIceGatheringStateComplete) {
        _localPeer.getLocalDescription().then((RTCSessionDescription desc) {
          channel.sink.add(
              json.encode({
                "type": "offer",
                "id": "$b",
                "message": {
                  "type": desc.type,
                  "sdp": desc.sdp,
                }
              })
          );
        });
      }
    };
    _localPeer.onIceCandidate = (RTCIceCandidate candidate) {
        json.encode({
          "type": "candidate",
          "id": "$b",
          "message": {
            "candidate": {
              "candidate": candidate.candidate,
              "sdpMid": candidate.sdpMid,
              "sdpMlineIndex": candidate.sdpMlineIndex
            }
          }
        });
    };
    _localPeer.onAddStream = (MediaStream m) async {
      _remoteContainer.srcObject = m;
    };
    _localPeer.onAddTrack = (MediaStream s, MediaStreamTrack t) {
      print(s);
      print(t);
    };
    _localPeer.createOffer({}).then((RTCSessionDescription desc) {
      _localPeer.setLocalDescription(desc);
    });
  }


  static void helloWorld() async {
    // PeerConnections
    RTCPeerConnection _localPeer;
    RTCPeerConnection _remotePeer;

    // VideoRenderers
    RTCVideoRenderer _remoteContainer = new RTCVideoRenderer();
    RTCVideoRenderer _localContainer = new RTCVideoRenderer();

    //socket
    IOWebSocketChannel channel;

    await initializeSocket(_remoteContainer, _localContainer, _localPeer, _remotePeer, channel);

    await initiateCall(_remoteContainer, _localContainer, _localPeer, _remotePeer, channel);

    await Future.delayed(Duration(days: 1));

  }
```

**Comment by cloudwebrtc** [comment]
@rushib1 I'm not sure if RTCVideoRenderer can be created in background mode, but I can be sure that removing `_remoteContainer.srcObject = m;` audio works fine, because the only effect here is to render the video.

**Comment by rushib1** [comment]
So we dont need containers to get audio? Just with rtcpeerConnections can we playback audio?

**Comment by cloudwebrtc** [comment]
Yes

**Comment by rushib1** [comment]
Thanks for the help.
