### ISSUE TITLE
FAILURE - build and deploy to iOS

### ISSUE THREAD

**Issue by lintonv** [cloudwebrtc/flutter-webrtc#38]
- Added flutter_webrtc to the pubpsec.yaml

- Updated  <project root>/ios/Runner/Info.plist

- Updated <project root>/android/app/src/main/AndroidManifest.xml

Then ran

```
flutter run -d all


Launching lib/main.dart on iPhone XR in debug mode...
2018-12-05 11:52:15.156 defaults[36085:1311989]
The domain/default pair of (/Users/lvadaked/src/flexlive/app/flexlive/ios/Runner/Info, CFBundleIdentifier) does not exist
E/flutter (25587): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (25587): NoSuchMethodError: The getter 'uid' was called on null.
E/flutter (25587): Receiver: null
E/flutter (25587): Tried calling: uid
E/flutter (25587): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (25587): #1      Auth.getCurrentUser (package:flexlive/auth.dart:26:17)
E/flutter (25587): <asynchronous suspension>
E/flutter (25587): #2      _RootPageState.initState (package:flexlive/root_page.dart:26:17)
E/flutter (25587): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter (25587): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (25587): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (25587): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (25587): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (25587): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (25587): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (25587): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (25587): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (25587): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (25587): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (25587): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (25587): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (25587): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (25587): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (25587): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (25587): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (25587): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (25587): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (25587): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (25587): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (25587): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (25587): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (25587): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (25587): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (25587): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (25587): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (25587): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (25587): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (25587): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (25587): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (25587): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (25587): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (25587): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (25587): #37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (25587): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (25587): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (25587): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (25587): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (25587): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (25587): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (25587): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (25587): #45     Element.inflateWidget (package:flutter/src/widgets/framew
Starting Xcode build...
 ├─Assembling Flutter resources...                    1.8s

 └─Compiling, linking and signing...                  2.4s

Xcode build done.                                            6.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code
    with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference"
    build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    While building module 'flutter_webrtc' imported from
    /Users/lvadaked/src/flexlive/app/flexlive/ios/Runner/GeneratedPluginRegistrant.m:7:
    In file included from <module-includes>:1:
    In file included from
    /Users/lvadaked/src/flexlive/app/flexlive/build/ios/Debug-iphonesimulator/flutter_webrtc/flutter_webrtc.framework/Headers/flutter_webr
    tc-umbrella.h:13:
    /Users/lvadaked/src/flexlive/app/flexlive/build/ios/Debug-iphonesimulator/flutter_webrtc/flutter_webrtc.framework/Headers/ARDVideoDeco
    derFactory.h:12:9: fatal error: 'WebRTC/RTCVideoCodecFactory.h' file not found
    #import "WebRTC/RTCVideoCodecFactory.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    /Users/lvadaked/src/flexlive/app/flexlive/ios/Runner/GeneratedPluginRegistrant.m:7:9: fatal error: could not build module
    'flutter_webrtc'
    #import <flutter_webrtc/FlutterWebRTCPlugin.h>
     ~~~~~~~^
    2 errors generated.

Could not build the application for the simulator.
Error launching application on iPhone XR.
 3.6s
```

**Comment by rostopira** [comment]
Try using master branch instead of current pub like this:
```yaml
  flutter_webrtc:
    git: https://github.com/rostopira/flutter-webrtc
```
Or remove `use_frameworks!` from your podfile

**Comment by lintonv** [comment]
Removing use_frameworks! from the podfile worked. Thanks @rostopira

**Comment by rostopira** [comment]
@lintonv so, master branch didn't worked?
Actually, it's well known flutter issue

**Comment by lintonv** [comment]
No, master branch did not work.
