### ISSUE TITLE
Missing Plugin Exception

### ISSUE THREAD

**Issue by kondanta** [cloudwebrtc/flutter-webrtc#69]
```
I/flutter ( 4819): ??? EXCEPTION CAUGHT BY SERVICES LIBRARY ???????????????????????????????????????????????????????????
I/flutter ( 4819): The following MissingPluginException was thrown while de-activating platform stream on channel
I/flutter ( 4819): cloudwebrtc.com/WebRTC/Texture26:
I/flutter ( 4819): MissingPluginException(No implementation found for method cancel on channel
I/flutter ( 4819): cloudwebrtc.com/WebRTC/Texture26)
I/flutter ( 4819): 
I/flutter ( 4819): When the exception was thrown, this was the stack:
I/flutter ( 4819): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
I/flutter ( 4819): <asynchronous suspension>
I/flutter ( 4819): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:502:29)
I/flutter ( 4819): <asynchronous suspension>
I/flutter ( 4819): #8      RTCVideoRenderer.dispose (package:flutter_webrtc/rtc_video_view.dart:81:25)
I/flutter ( 4819): <asynchronous suspension>
I/flutter ( 4819): #9      _VoipConnectionState.deactivate
```
This occurs when I try to close the page that contains video chat elements in it.

**Comment by cloudwebrtc** [comment]
Can you provide some code segment? it looks like the dispose is called twice.

**Comment by kondanta** [comment]
Sure! 

This is the the segment that responsible from calling the RTC class
```dart
class PP extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider<PBloc>(
      bloc: PBloc(),
      child: DefaultTabController(
        length: 2,
        child: Scaffold(
          //backgroundColor: Colors.black,
          body: TabBarView(
            children: <Widget>[
              PatientDashboardBuilder(),
              RTC(),
            ],
          ),
          bottomNavigationBar: TabBar(
            labelColor: Colors.white,
            tabs: [
              Tab(
                icon: Icon(Icons.home),
                text: "Dashboard",
              ),
              Tab(
                icon: Icon(Icons.video_call),
                text: "RTC",
              ),
            ],
          ),
          backgroundColor: HexColor("#0f1923"),
        ),
      ),
    );
  }
}
```

and this is the whole RTC class. I actually copied this from webrtc-flutter-demo repository. 

```dart
class RTC extends StatefulWidget {
  static String tag = 'call';

  // Needs to be set in here.
  final String ip = '<flutter-webrtc-server ip>';

  final P p;
  final D d;
  final bool isD;

  RTC({Key key, this.patient, this.doctor, @required this.isDoctor})
      : super(key: key);

  @override
  _RTCState createState() => _RTCState(serverIP: ip);
}

class _RTCState extends State<RTC> {
  Signaling _signaling;
  String _displayName =
      Platform.localHostname + '(' + Platform.operatingSystem + ")";
  List<dynamic> _peers;
  var _selfId;
  RTCVideoRenderer _localRenderer = RTCVideoRenderer();
  RTCVideoRenderer _remoteRenderer = RTCVideoRenderer();
  bool _inCalling = false;
  final String serverIP;
  final Future<String> userId = new Auth().getUser();
  bool isOnline;

  _VoipConnectionState({Key key, @required this.serverIP});

  @override
  initState() {
    super.initState();
    initRenderers();
    _connect();
    _selfId = _initUserName();
    isOnline = false;
  }

  _initUserName() async {
    String _id;
    _id = await userId;
    return _id;
  }

  initRenderers() async {
    await _localRenderer.initialize();
    await _remoteRenderer.initialize();
  }

  @override
  void dispose() {
    if (_signaling != null) _signaling.close();
    _localRenderer.dispose();
    _remoteRenderer.dispose();
    super.dispose();
  }

  void _connect() async {
    if (_signaling == null) {
      _signaling = Signaling('ws://' + serverIP + ':4442', _displayName)
        ..connect();

      _signaling.onStateChange = (SignalingState state) {
        switch (state) {
          case SignalingState.CallStateNew:
            this.setState(() {
              _inCalling = true;
            });
            break;
          case SignalingState.CallStateBye:
            this.setState(() {
              _localRenderer.srcObject = null;
              _remoteRenderer.srcObject = null;
              _inCalling = false;
            });
            break;
          case SignalingState.CallStateInvite:
          case SignalingState.CallStateConnected:
          case SignalingState.CallStateRinging:
          case SignalingState.ConnectionClosed:
          case SignalingState.ConnectionError:
          case SignalingState.ConnectionOpen:
            break;
        }
      };

      _signaling.onPeersUpdate = ((event) {
        print(event['peers']);
        this.setState(() {
          //_selfId = event['self'];
          _peers = event['peers'];
        });
      });

      _signaling.onLocalStream = ((stream) {
        _localRenderer.srcObject = stream;
      });

      _signaling.onAddRemoteStream = ((stream) {
        _remoteRenderer.srcObject = stream;
      });

      _signaling.onRemoveRemoteStream = ((stream) {
        _remoteRenderer.srcObject = null;
      });
    }
  }

  _invitePeer(context, peerId, useScreen) async {
    if (_signaling != null && peerId != _selfId) {
      _signaling.invite(peerId, 'video', useScreen);
    }
  }

  _hangUp() {
    if (_signaling != null) {
      _signaling.bye();
    }
  }

  _switchCamera() {
    _signaling.switchCamera();
  }

  _muteMic() {}

  @override
  Widget build(BuildContext context) {
    final List availableEntities = _buildPatientPeerMergedList(_peers,
        widget.isDoctor ? widget.doctor.patientId : widget.patient.doctorId);
    return Scaffold(
      appBar: AppBar(
        title: Text('Users on VOIP Server'),
        backgroundColor: HexColor("#0f1923"),
        actions: <Widget>[
          IconButton(
            icon: const Icon(Icons.settings),
            onPressed: null,
            tooltip: 'setup',
          ),
        ],
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      floatingActionButton: _inCalling
          ? SizedBox(
          width: 200.0,
          child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                FloatingActionButton(
                  child: const Icon(Icons.switch_camera),
                  onPressed: _switchCamera,
                ),
                FloatingActionButton(
                  onPressed: _hangUp,
                  tooltip: 'Hangup',
                  child: Icon(Icons.call_end),
                  backgroundColor: Colors.pink,
                ),
                FloatingActionButton(
                  child: const Icon(Icons.mic_off),
                  onPressed: _muteMic,
                )
              ]))
          : null,
      body: _inCalling
          ? OrientationBuilder(builder: (context, orientation) {
        return Container(
          child: Stack(children: <Widget>[
            Positioned(
                left: 0.0,
                right: 0.0,
                top: 0.0,
                bottom: 0.0,
                child: Container(
                  margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  width: MediaQuery.of(context).size.width,
                  height: MediaQuery.of(context).size.height,
                  child: RTCVideoView(_remoteRenderer),
                  decoration: BoxDecoration(color: Colors.black54),
                )),
            Positioned(
              left: 20.0,
              top: 20.0,
              child: Container(
                width: orientation == Orientation.portrait ? 90.0 : 120.0,
                height:
                orientation == Orientation.portrait ? 120.0 : 90.0,
                child: RTCVideoView(_localRenderer),
                decoration: BoxDecoration(color: Colors.black54),
              ),
            ),
          ]),
        );
      })
          : 
      ListView.builder(
        padding: const EdgeInsets.symmetric(
          vertical: 50.0,
          horizontal: 15.0,
        ),
        shrinkWrap: true,
        itemCount: widget.isEntity
            ? widget.d.pId.length
            : widget.p.dId.length,
        physics: const BouncingScrollPhysics(),
        scrollDirection: Axis.horizontal,
        itemBuilder: (context, i) {
          return Container(
            margin: const EdgeInsets.symmetric(horizontal: 10.0),
            width: 230.0,
            height: 200.0,
            decoration: BoxDecoration(
              color: _colorBuilder(availableEntities),
              borderRadius: BorderRadius.all(Radius.circular(120.0)),
            ),
            child: _testChildBuilder(widget.isEntity
                ? widget.d.pId[i]
                : widget.p.dId[i]),
          );
        },
      ),
    );
  }
}
```

**Comment by cloudwebrtc** [comment]
It looks like a bug, I will try to fix it.

**Comment by cgbrucezjy** [comment]
same issue here when trying to call _localRenderer.dispose(); on deactivate

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/cloudwebrtc/flutter-webrtc/commit/11fe6ab0612ffd1712c09b72339f76d717ca5959.
