### ISSUE TITLE
Exception on flutter v1.5

### ISSUE THREAD

**Issue by cloudwebrtc** [cloudwebrtc/flutter-webrtc#87]
Running an exception on flutter v1.5, it seems that we need to use Main Thread to callback the result of MethodChannel/EventChannel.

```
W/System.err( 5858): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: signaling_threa - 5899
W/System.err( 5858):    at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/System.err( 5858):    at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
W/System.err( 5858):    at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
W/System.err( 5858):    at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:149)
W/System.err( 5858):    at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:142)
W/System.err( 5858):    at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:223)
W/System.err( 5858):    at com.cloudwebrtc.webrtc.PeerConnectionObserver.sendEvent(PeerConnectionObserver.java:332)
W/System.err( 5858):    at com.cloudwebrtc.webrtc.PeerConnectionObserver.onRenegotiationNeeded(PeerConnectionObserver.java:425)
```

**Comment by rostopira** [comment]
It's not the only place where it crashes, it's a lot of calls everywhere
If it was Kotlin, I would create extension method like `.successOnUiThread()`, something like that
But in Java wrapping every single single in static method... That would be ugly as hell
Any ideas on how this should be implemented?

**Comment by rostopira** [comment]
Suggestion, wrap every `Result` object in this:
```java
public final class AnyThreadResult implements MethodChannel.Result {
    final private MethodChannel.Result result;
    
    AnyThreadResult(MethodChannel.Result result) {
        this.result = result;
    }
    
    @Override
    public void success(Object o) {
        final Handler handler = new Handler(Looper.getMainLooper());
        handler.post(()->result.success(o));
    }

    @Override
    public void error(String s, String s1, Object o) {
        final Handler handler = new Handler(Looper.getMainLooper());
        handler.post(()->result.error(s, s1, o));
    }

    @Override
    public void notImplemented() {
        final Handler handler = new Handler(Looper.getMainLooper());
        handler.post(result::notImplemented);
    }
}
```

**Comment by cloudwebrtc** [comment]
Yes, and ```eventSink``` also needs the same processing. All webrtc events are triggered by the source_thread from the native. Basically all ```result``` and ```eventSink``` need to be processed.

**Comment by rostopira** [comment]
Well, unless someone wants to do that, I will start working on it in few days

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/cloudwebrtc/flutter-webrtc/commit/a15119730e3f4652fdf4451333ab2a11a9ebaade
