### ISSUE TITLE
MissingPluginException when calling dispose of RTCVideoRenderer

### ISSUE THREAD

**Issue by ZeBrody** [cloudwebrtc/flutter-webrtc#94]
I get a MissingPluginException when calling the dispose function of the RTCVideoRenderer object.
This also happenes in the WebRTC Demo

```
 ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (10816): The following MissingPluginException was thrown while de-activating platform stream on channel
I/flutter (10816): cloudwebrtc.com/WebRTC/Texture0:
I/flutter (10816): MissingPluginException(No implementation found for method cancel on channel
I/flutter (10816): cloudwebrtc.com/WebRTC/Texture0)
I/flutter (10816): 
I/flutter (10816): When the exception was thrown, this was the stack:
I/flutter (10816): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
I/flutter (10816): <asynchronous suspension>
I/flutter (10816): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:502:29)
I/flutter (10816): <asynchronous suspension>
I/flutter (10816): #8      RTCVideoRenderer.dispose (package:flutter_webrtc/rtc_video_view.dart:76:25)
I/flutter (10816): <asynchronous suspension>
I/flutter (10816): #9      _MyAppState.deactivate (package:flutter_webrtc_demo/src/basic_sample/loopback_sample.dart:36:20)
I/flutter (10816): #10     StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:3909:12)
I/flutter (10816): #11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1715:13)
I/flutter (10816): #12     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10816): #13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10816): #17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10816): #19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10816): #21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #22     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10816): #23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10816): #31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10816): #35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #39     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10816): #41     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #43     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #45     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10816): #47     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (10816): #48     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1726:7)
I/flutter (10816): #49     Element.deactivateChild (package:flutter/src/widgets/framework.dart:2997:29)
I/flutter (10816): #50     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4694:11)
I/flutter (10816): #51     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (10816): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (10816): #53     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
I/flutter (10816): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (10816): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (10816): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (10816): #57     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (10816): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (10816): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (10816): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (10816): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (10816): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (10816): #66     _invoke (dart:ui/hooks.dart:219:10)
I/flutter (10816): #67     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (10816): (elided 9 frames from package dart:async)
I/flutter (10816): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
Steps to reproduce:

Start the Demo
Select Basic API Tests, LoopBack Sample
Navigate back

* **Flutter version**:  Flutter version 1.5.4-hotfix.2 at C:\Flutter SDK\flutter
* **Plugin version**: 0.1.6
* **OS**: Android 
* **OS version**: 8.0.0

**Comment by cloudwebrtc** [comment]
Already fixed in https://github.com/cloudwebrtc/flutter-webrtc/commit/11fe6ab0612ffd1712c09b72339f76d717ca5959, but need to wait for the release of 0.1.7 to take effect.
